---
version: "3.9"

name: gamejammers

services:
  db:
    container_name: gamejammers_db
    image: postgres:14
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    networks:
      - internal_network
    restart: unless-stopped

  app:
    platform: "linux/amd64"
    image: t3-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "{APP_PORT:-3000}:3000"
    networks:
      - internal_network
      - external_network
    environment:
      - DATABASE_URL=postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}
    env_file:
      - .env

networks:
  external_network:
  internal_network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
