---
version: "3.9"

name: gamejammers

services:
  db:
    container_name: gamejammers_db
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=pass
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    networks:
      - internal_network
    restart: unless-stopped

  app:
    container_name: gamejammers_app
    image: gamejammers:dev
    depends_on:
      - db
    build:
      context: .
    ports:
      - ${APP_PORT:-3000}:3000
      - ${PRISMA_PORT:-5555}:5555
    volumes:
      - .:/code/
    networks:
      - internal_network
      - external_network
    environment:
      - DATABASE_URL=postgresql://user:pass@db/db
    env_file:
      - .env
    restart: unless-stopped

networks:
  external_network:
  internal_network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
